

## try this in general and with enable_some_zen.yml it might be differnet than bellow
# filter_title: Zen
# filter_class: zen
# enable: false

## here is how to get ].f] work
# filter_title: Zen
filter_class: Alacritty
extra_includes:
extra_excludes:
  - "../match/001-esentials/typosfix-when-no-package.yml"
